name: gooddeal
description: "굿딜 - 최저가 쇼핑 가격 추적 앱"
publish_to: 'none'
version: 1.1.0+7

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  cached_network_image: ^3.3.1
  intl: ^0.20.0
  shared_preferences: ^2.3.0
  flutter_riverpod: ^2.6.0
  url_launcher: ^6.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  flutter_staggered_grid_view: ^0.7.0
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4
  cloud_firestore: ^5.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter:
  uses-material-design: true
